# Generated by Django 5.2 on 2025-11-23 17:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Правовые документы', max_length=255, verbose_name='Название компании (Заголовок)')),
                ('contact_info', models.TextField(default='info@pravo-dok.ru', verbose_name='Контакты (Email/Адрес)')),
                ('copyright_text', models.CharField(default='© 2025 Все права защищены', max_length=255, verbose_name='Копирайт')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='FooterMainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Text')),
                ('link_exteranl', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Внутренняя страница')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='site_settings.footersettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
