# Generated by Django 5.2 on 2025-11-23 17:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footermainlink',
            old_name='link_exteranl',
            new_name='link_external',
        ),
        migrations.RemoveField(
            model_name='footermainlink',
            name='title',
        ),
        migrations.AddField(
            model_name='footermainlink',
            name='link_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст ссылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footermainlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_links', to='site_settings.footersettings'),
        ),
        migrations.CreateModel(
            name='FooterLegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(max_length=255, verbose_name='Текст ссылки')),
                ('link_external', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Внутренняя страница')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='site_settings.footersettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
