# Generated by Django 5.2 on 2025-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
