# Generated by Django 5.2 on 2025-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Файл'),
        ),
    ]
