# Generated by Django 5.2 on 2025-06-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_instructions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='categories.category', verbose_name='Категория'),
        ),
    ]
