# Generated by Django 5.2 on 2026-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_documents_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Одно-два предложения под заголовком категории или подраздела', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Одно-два предложения: показывается в карточке и под заголовком документа', verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='documents',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число страниц'),
        ),
        migrations.AddField(
            model_name='documents',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='categories.tag', verbose_name='Теги'),
        ),
    ]
