networks:
  lawyers_network:
    driver: bridge

services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      LANG: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/psql:/var/lib/postgresql/data
    networks:
      - lawyers_network
  api:
    container_name: api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./docker_data/static:/app/static
    depends_on:
      - database
    command: gunicorn lawyers_back.wsgi:application --bind 0.0.0.0:8000
    networks:
      - lawyers_network
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - lawyers_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker_data/certbot:/var/www/certbot
      - ./docker_data/letsencrypt:/etc/letsencrypt
      - ./docker_data/static:/app/static
    depends_on:
      - api
      - web
    networks:
      - lawyers_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker_data/letsencrypt:/etc/letsencrypt
      - ./docker_data/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1 & wait $!; done;'"
    networks:
      - lawyers_network