# Generated by Django 5.2 on 2025-11-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wag', '0003_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
