# Generated by Django 5.2 on 2025-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Путь страгицы (без начального "/", например: about, categories/слаг категории)', max_length=255, verbose_name='Путь')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
            ],
        ),
    ]
