# Generated by Django 5.2 on 2025-11-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatags',
            options={'verbose_name': 'Мета Тег', 'verbose_name_plural': 'Мета Теги'},
        ),
    ]
