# Generated by Django 5.2 on 2025-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True, verbose_name='ID заказа')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email пользователя')),
                ('description', models.CharField(blank=True, max_length=155, null=True, verbose_name='Описание заказа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплачен')),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Завершен')),
                ('is_canceled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отменен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
