# Generated by Django 5.2 on 2026-04-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0005_alter_documents_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('description', models.TextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_instruction', to='categories.documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Статья инструкция к определенному документу',
                'verbose_name_plural': 'Статьи инструкции к определенным документам',
            },
        ),
        migrations.CreateModel(
            name='DocumentSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar', to='categories.documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Левая колонка документа',
                'verbose_name_plural': 'Левые колонки документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentSidebarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('section_type', models.CharField(choices=[('instruction', 'Инструкция'), ('data', 'Данные'), ('tips', 'Советы'), ('other', 'Другое')], default='other', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('sidebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='static_components.documentsidebar')),
            ],
            options={
                'verbose_name': 'Секция левой колонки',
                'verbose_name_plural': 'Секции левой колонки',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentSidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='static_components.documentsidebarsection')),
            ],
            options={
                'verbose_name': 'Пункт секции левой колонки',
                'verbose_name_plural': 'Пункты секций левой колонки',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
